# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
org: udea20252
app: taskmaster-api
service: taskmaster-api

provider:
  name: aws
  runtime: nodejs22.x
  timeout: 10
  region: us-east-1

  environment:
    TASKS_TABLE: Tasks

  # Permisos IAM para las funciones Lambda
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TASKS_TABLE}"

plugins:
  - serverless-offline

functions:
  # GET /tasks - Obtener todas las tareas
  getTasks:
    handler: handler.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get

  # GET /tasks/{id} - Obtener una tarea espec√≠fica
  getTask:
    handler: handler.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get

  # POST /tasks - Crear nueva tarea
  createTask:
    handler: handler.createTask
    events:
      - httpApi:
          path: /tasks
          method: post

  # PUT /tasks/{id} - Actualizar tarea
  updateTask:
    handler: handler.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put

  # DELETE /tasks/{id} - Eliminar tarea
  deleteTask:
    handler: handler.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete

# Recursos de infraestructura (DynamoDB)
resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TASKS_TABLE}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    tables:
      - TasksTable

  serverless-offline:
    httpPort: 3001
